name1 = String.new('sanghyup')
name2 = String.new('sanghyup1')
puts(name1.reverse())
puts(name2.reverse())
puts(name1.upcase())
puts(name1.size())
names = Array.new()
names.push('sanghyup')
names.push('sanghyup1')
puts(names)
puts(names.join(','))
